### ISSUE TITLE
ヒットアンドブローのルール

### ISSUE THREAD

**Issue by Takatatsu9** [danielkaneko/HitAndBlow#1]
- 0～9までの数字4桁を当てるゲーム
- 桁違いの一致は「ブロー」、桁まで一致したら「ヒット」としてカウントする
- 4ヒットでゲームクリア

**Comment by danielkaneko** [comment]
現在、gitをダウンロードした後、インストールまで進めたのですがインストール後、gitbashへどのようにアクセスすればいいのかわからず止まっています。教えていただけないでしょうか？

**Comment by Takatatsu9** [comment]
インストール完了したならば、スタートメニューのアプリ一覧に`git`フォルダ、その中に`git bash`があるはずです。
Win11なら、スタートメニューの検索で`git`と打ってみてください。
他にも、右クリックメニューに`Git Bash Here`が追加されるはずです。

**Comment by danielkaneko** [comment]
ありがとうございます。
gitフォルダが見当たらないのでインストールが正しく行えていなかったのだと思います。
もう一度インストールを試してみます。

**Comment by Takatatsu9** [comment]
もし何度か試してみてだめだったらビデオ会議で確認するので、その場合は声かけてください。

**Comment by danielkaneko** [comment]
インストール無事できました。
ありがとうございます。

**Comment by danielkaneko** [comment]
ヒット＆ブローのCPUが決める数字4桁に重複除外処理は必要でしょうか？
また、プレイヤーが入力した数字にも重複除外処理は必要でしょうか？
作業を始める前に高橋さんに確認を取るべきでした、申し訳ありません。

**Comment by Takatatsu9** [comment]
答えの数値に対しては必要ですが、プレイヤーの入力に関しては不要です。

**Comment by danielkaneko** [comment]
ありがとうございます。
