### ISSUE TITLE
数値入力受付の形式

### ISSUE THREAD

**Issue by Takatatsu9** [danielkaneko/HitAndBlow#10]
`数値を入力してください：〜`がいい

**Comment by Takatatsu9** [comment]
ひとつ追記しておくと、これは仕様変更ではありません。
「こういうのが来ると思ってたのに違うものが上がってきた」という指摘のようなものです。

**Comment by danielkaneko** [comment]
受付メッセージの表示の仕方について質問させていただきたいのですが、
「数値を入力してください：」のメッセージの後は改行せずに入力を受け付けるという認識でお間違いないでしょうか。

**Comment by Takatatsu9** [comment]
そのとおりです。

**Comment by danielkaneko** [comment]
ありがとうございます。
承知いたしました。
