### ISSUE TITLE
答えを見る隠し機能が欲しい

### ISSUE THREAD

**Issue by nabemasamasa** [danielkaneko/HitAndBlow#3]
`ShowAnswer`と入力したら、答えを表示する

**Comment by danielkaneko** [comment]
機能について質問させていただきたいのですが、
小文字でshowanswerと入力された場合にも答えを表示しますか。

**Comment by Takatatsu9** [comment]
表示しません。大文字小文字完全一致のみです。

**Comment by danielkaneko** [comment]
ありがとうございます。

**Comment by danielkaneko** [comment]
機能について質問させていただきたいのですが、
答えを表示した後、数字を入力し回答することはできますか。

**Comment by Takatatsu9** [comment]
はい、できます。これは動作検証用の機能ですので。

**Comment by danielkaneko** [comment]
ありがとうございます。
