### ISSUE TITLE
ギブアップ機能

### ISSUE THREAD

**Issue by nabemasamasa** [danielkaneko/HitAndBlow#4]
`giveup`と入力したら、答えを表示してゲームを終了する

**Comment by danielkaneko** [comment]
giveupの機能は、ShowAnswerと同様に大文字小文字完全一致で入力された場合のみゲームが終了するのでしょうか。

**Comment by Takatatsu9** [comment]
ギブアップは大文字小文字無視です。`gIVeuP`と入力しても受け付けます。

**Comment by danielkaneko** [comment]
ありがとうございます。
