### ISSUE TITLE
クリアタイム表示機能

### ISSUE THREAD

**Issue by nabemasamasa** [danielkaneko/HitAndBlow#5]
ゲームを開始してからクリアするまでの時間を表示したい

**Comment by danielkaneko** [comment]
クリアタイムの表示の仕方に規定はありますか。

**Comment by Takatatsu9** [comment]
規定とは何を指していますか？

**Comment by danielkaneko** [comment]
12分34秒とクリアタイムを表示するのか、12'34と表示するのか、それ以外で表示するのかということです。

**Comment by Takatatsu9** [comment]
`分:秒.ミリ秒`でお願いします

**Comment by danielkaneko** [comment]
ありがとうございます。
承知いたしました。

**Comment by danielkaneko** [comment]
クリアタイムの表示に、「イメージと違う」というご意見を頂きましたが、表示の仕方にご希望はございますか？
例：「クリアタイムは○○:○○.○○」「ゲーム開始から○○:○○.○○経過しました」等

**Comment by Takatatsu9** [comment]
`クリアタイム　○○:○○.○○`でお願いします。

**Comment by danielkaneko** [comment]
承知いたしました。
