### ISSUE TITLE
正解まで何手かかったか表示する機能

### ISSUE THREAD

**Issue by nabemasamasa** [danielkaneko/HitAndBlow#6]
クリア時に正解するまで何回入力したかの回数を表示したい

**Comment by danielkaneko** [comment]
機能について質問させていただきたいのですが、
クリアタイムとどちらを先に表示すべきでしょうか。

**Comment by Takatatsu9** [comment]
手数が先がいいです。

**Comment by danielkaneko** [comment]
ありがとうございます。
入力回数のカウントは、回答として適切な入力が行われた場合のみカウントするという認識でよろしいでしょうか。

**Comment by Takatatsu9** [comment]
そうです。

**Comment by danielkaneko** [comment]
入力回数の表示の仕方について質問をさせていただきたいのですが、
表示をする際に入力回数のほかにメッセージは必要でしょうか。
例（〇〇回入力しました。）（入力回数は〇〇）等

**Comment by Takatatsu9** [comment]
「◯手」でお願いします

**Comment by danielkaneko** [comment]
承知いたしました。

**Comment by danielkaneko** [comment]
メッセージの表示について質問したいのですが、「〇手」のみではなく、「正解まで〇手かかりました。」というメッセージを表示したいのですが、よろしいでしょうか。

**Comment by Takatatsu9** [comment]
なぜでしょうか？「◯手」がいいです。

**Comment by danielkaneko** [comment]
クリア後に「◯手」とだけ表示された際に、初見ですとユーザーがそのメッセージを「正解までにかかった手数」と判断できない可能性があるためです。

**Comment by Takatatsu9** [comment]
私は「クリア（あるいは正解）まで：◯手」と表示することを想像してたのですけど

**Comment by danielkaneko** [comment]
ご希望をくみ取ることができず、大変申し訳ございませんでした。
メッセージを「クリア（あるいは正解）まで：◯手」と表示する形で作業を進めさせていただきます。
