### ISSUE TITLE
挑戦桁数変更

### ISSUE THREAD

**Issue by nabemasamasa** [danielkaneko/HitAndBlow#7]
ゲーム開始時に、桁数を3〜10桁まで選んで挑戦したい

**Comment by danielkaneko** [comment]
機能について質問したいのですが、
・桁数を入力する際のメッセージはどのような文章がよろしいでしょうか。
例（問題桁数：）（挑戦する問題の桁数を入力してください）等
・挑戦する桁数を入力する際、3～１０以外の数字が入力された際の処理はどのようにいたしますか
例（正しい入力がされるまで繰り返し入力を促す。）（入力内容が正しくないという内容のメッセージを表示し、ゲームを終了する）
・挑戦する桁数を入力する際、ギブアップ機能のように桁数を入力をせずにゲームを終了する手段は必要でしょうか。

**Comment by Takatatsu9** [comment]
```
1. XXX
2. YYY
3. ZZZ
```
って書くと
1. XXX
2. YYY
3. ZZZ

と（分かり辛いけど）段落表示できるので、そうすると回答するときどれがどれにあたるか見やすいので次からそう書いてください

**Comment by Takatatsu9** [comment]
1. 後者がいいです。
2. 前者がいいです。
3. 不要ですが、あってもいいです。

**Comment by danielkaneko** [comment]
ありがとうございます。
承知いたしました。

**Comment by danielkaneko** [comment]
機能について質問したいのですが、

1. 挑戦する桁数を入力した際に、入力された数字が２以下または10以上だった場合にメッセージを表示する必要はありますか。もしも必要であれば、どのようなメッセージを表示すればよいでしょうか。
例（3～10までの数字を入力してください）（3桁～10桁でしかプレイできません）等
2. 挑戦する桁数を入力した際に、入力された数字に数字以外が含まれていた場合場合にメッセージを表示する必要はありますか。もしも必要であれば、どのようなメッセージを表示すればよいでしょうか。
例（3～10までの数字を入力してください）（数字以外の文字が入力されています）

**Comment by Takatatsu9** [comment]
1. 前者です。同じ質問を再び表示してください。
2. 1と同様です。

**Comment by danielkaneko** [comment]
ありがとうございます。
承知いたしました。

**Comment by danielkaneko** [comment]
挑戦する桁数を入力する際、ギブアップ機能のように桁数を入力をせずにゲームを終了する機能の追加を考えているのですが、入力する文字列に指定はございますか。

**Comment by Takatatsu9** [comment]
お任せします。

**Comment by danielkaneko** [comment]
承知いたしました。
